"""
Figure 1 — Extropic Z-1 "G_12" native connectivity (arXiv:2510.23972, Table 2).

Pure-plotting illustration (no compute, no training). Two panels:
  LEFT  — the degree-12 connectivity stencil: a central pbit at (0,0) coupled to
          12 neighbours generated by three "connection rules", each a base offset
          (a,b) plus its three 90-degree rotations.
  RIGHT — a checkerboard coloured by (x+y) % 2 showing that every rule has a+b odd,
          so all 12 neighbours land on the opposite colour => bipartite => the chip
          runs a 2-colour block-Gibbs cycle.

Run:  /Users/kamp/Documents/energy/.venv/bin/python figures/make_01_connectivity.py
"""
import matplotlib
matplotlib.use("Agg")
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle

# ---- shared style -----------------------------------------------------------
WARM   = "#ffb703"   # logic / +1 / rule (0,1)
COOL   = "#4cc9f0"   # prob / -1 / rule (4,1)
TEAL   = "#2ec4b6"   # accent / rule (9,10)
HILITE = "#ef476f"   # highlight / positive
TEXT   = "#e6ebf5"   # text (light)
EDGE   = "#475569"   # edges / lines (dark-mode)
GRID   = "#22304d"   # dark grid
CENTER = "#fb8500"   # center / special

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.size": 10,
    "figure.facecolor": "#0f1420", "axes.facecolor": "#0f1420", "savefig.facecolor": "#0f1420",
    "text.color": "#e6ebf5", "axes.labelcolor": "#e6ebf5", "axes.titlecolor": "#e6ebf5",
    "axes.edgecolor": "#475569", "xtick.color": "#cbd5e1", "ytick.color": "#cbd5e1", "grid.color": "#22304d",
})


def rotations90(a, b):
    """A base offset (a,b) and its three 90-degree rotations -> 4 offsets."""
    return [(a, b), (-b, a), (-a, -b), (b, -a)]


# The three documented G_12 connection rules (base offset -> 4 neighbours each).
RULES = [
    {"base": (0, 1),  "color": WARM, "label": r"rule $(0,1)$ — orthogonal NN (len $1$)"},
    {"base": (4, 1),  "color": COOL, "label": r"rule $(4,1)$ — skew skip (len $\sqrt{17}\approx4.1$)"},
    {"base": (9, 10), "color": TEAL, "label": r"rule $(9,10)$ — skew skip (len $\sqrt{181}\approx13.5$)"},
]
for r in RULES:
    r["offsets"] = rotations90(*r["base"])


def panel_left(ax):
    ax.set_title("Z-1 'G$_{12}$' connectivity: 12 couplings + self-bias",
                 fontsize=12, fontweight="bold", pad=10)

    # light integer grid
    for k in range(-11, 12):
        ax.axhline(k, color=GRID, lw=0.6, zorder=0)
        ax.axvline(k, color=GRID, lw=0.6, zorder=0)

    # edges + neighbour dots, coloured by rule
    for r in RULES:
        for (dx, dy) in r["offsets"]:
            ax.plot([0, dx], [0, dy], color=r["color"], lw=1.2, alpha=0.85, zorder=2)
        xs = [o[0] for o in r["offsets"]]
        ys = [o[1] for o in r["offsets"]]
        ax.scatter(xs, ys, s=90, color=r["color"], edgecolors="#e6ebf5",
                   linewidths=1.0, zorder=3)

    # central pbit (self-bias)
    ax.scatter([0], [0], s=320, color=CENTER, edgecolors="#e6ebf5",
               linewidths=1.6, zorder=4)
    ax.annotate("central pbit\n(self-bias)", xy=(0, 0), xytext=(0.7, -2.4),
                fontsize=9, color=CENTER, ha="left", fontweight="bold")

    ax.set_xlim(-11, 11)
    ax.set_ylim(-11, 11)
    ax.set_aspect("equal")
    ax.set_xticks(range(-10, 11, 5))
    ax.set_yticks(range(-10, 11, 5))
    ax.set_xlabel("x offset")
    ax.set_ylabel("y offset")

    handles = [Line2D([0], [0], marker="o", color="none", markerfacecolor=r["color"],
                      markeredgecolor="#e6ebf5", markersize=9, label=r["label"])
               for r in RULES]
    handles.append(Line2D([0], [0], marker="o", color="none", markerfacecolor=CENTER,
                          markeredgecolor="#e6ebf5", markersize=11,
                          label="central pbit + self-bias"))
    leg = ax.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, -0.13),
                    fontsize=8.5, frameon=False, ncol=1, handletextpad=0.5)
    for t in leg.get_texts():
        t.set_color("#e6ebf5")


def panel_right(ax):
    ax.set_title("Bipartite by construction", fontsize=12, fontweight="bold", pad=10)

    # 9x9 checkerboard centred on (0,0): cells x,y in [-4..4]
    rng = range(-4, 5)
    shade0, shade1 = "#1b2336", "#0f1420"  # two dark, distinguishable shades
    for x in rng:
        for y in rng:
            c = shade0 if (x + y) % 2 == 0 else shade1
            ax.add_patch(Rectangle((x - 0.5, y - 0.5), 1, 1,
                                    facecolor=c, edgecolor="#475569", lw=0.8, zorder=0))

    # center cell marker (lives on the (x+y) even colour)
    ax.scatter([0], [0], s=300, color=CENTER, edgecolors="#e6ebf5",
               linewidths=1.6, zorder=4)

    # overlay the 4 orthogonal NN + a couple of skew neighbours that fit the 9x9 box
    show = list(RULES[0]["offsets"])                 # 4 orthogonal NN
    show += [o for o in RULES[1]["offsets"]
             if abs(o[0]) <= 4 and abs(o[1]) <= 4]   # in-frame skew (4,1) skips
    for (dx, dy) in show:
        ax.plot([0, dx], [0, dy], color=EDGE, lw=1.1, alpha=0.85, zorder=2)
        ax.scatter([dx], [dy], s=110, color=HILITE, edgecolors="#e6ebf5",
                   linewidths=1.1, zorder=3)

    ax.set_xlim(-4.5, 4.5)
    ax.set_ylim(-4.5, 4.5)
    ax.set_aspect("equal")
    ax.set_xticks(range(-4, 5, 2))
    ax.set_yticks(range(-4, 5, 2))
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    # annotation below the panel
    ax.annotate(
        "every rule has  $a+b$  odd  $\\Rightarrow$  all 12 neighbours are the\n"
        "opposite colour  $\\Rightarrow$  bipartite  $\\Rightarrow$  2-colour block Gibbs",
        xy=(0.5, -0.18), xycoords="axes fraction", ha="center", va="top",
        fontsize=9, color=TEXT)

    handles = [
        Line2D([0], [0], marker="s", color="none", markerfacecolor=shade0,
               markeredgecolor="#64748b", markersize=11, label="colour A   $(x+y)$ even"),
        Line2D([0], [0], marker="s", color="none", markerfacecolor=shade1,
               markeredgecolor="#64748b", markersize=11, label="colour B   $(x+y)$ odd"),
        Line2D([0], [0], marker="o", color="none", markerfacecolor=CENTER,
               markeredgecolor="#e6ebf5", markersize=11, label="central pbit"),
        Line2D([0], [0], marker="o", color="none", markerfacecolor=HILITE,
               markeredgecolor="#e6ebf5", markersize=9,
               label="neighbours (all opposite colour)"),
    ]
    leg = ax.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, -0.30),
                    fontsize=8.5, frameon=False, ncol=1, handletextpad=0.5)
    for t in leg.get_texts():
        t.set_color("#e6ebf5")


def main():
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(8, 5))
    panel_left(axL)
    panel_right(axR)
    fig.suptitle("Extropic Z-1 native connectivity (arXiv:2510.23972, Table 2)",
                 fontsize=14, fontweight="bold", y=1.02)
    fig.subplots_adjust(wspace=0.32, bottom=0.30, top=0.90)

    out = "figures/01_z1_connectivity.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    print("wrote", out)


if __name__ == "__main__":
    main()
